import Head from 'next/head';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import MainContent from '@/components/MainContent';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>JHON MARK VALDEZ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-screen font-bodyFont bg-[#0A192F] text-[#ccd6f6] overflow-x-hidden overflow-y-scroll scrollbar scrollbar-track-teal-600/20 scrollbar-thumb-teal-600">
        <Navbar />
        <MainContent />
      </main>
    </>
  );
}
